### ISSUE TITLE
Mapping from entity to types

### ISSUE THREAD

**Issue by ameyagodbole** [tsafavi/codex#1]
Thank you for curating and releasing this dataset. I was trying to use the `types.json` mapping but I am not sure how I can map entities to their types using the dataset. Any suggestions?

**Comment by tsafavi** [comment]
Hi @ameyagodbole, thanks for your interest! In the `data/types/` directory, there should be a file called `entity2types.json`, which maps each entity ID to a list of entity types (which are also Wikidata entity IDs). [The README](https://github.com/tsafavi/codex#entities-and-entity-types) also gives information on the structure. Let me know if you have questions.

**Comment by ameyagodbole** [comment]
I was looking under `en` and missed the parent directory.
Sorry for the redundant question. Thanks
