### ISSUE TITLE
Make license more explicit

### ISSUE THREAD

**Issue by rhofour** [tsafavi/codex#3]
It appears this code is licensed under the MIT license (according to the license field in setup.py), but this isn't very clear. I would like to use this code in my workplace, but I need to know how's it's licensed before I can do that. If this is intended to be MIT licensed can you make this more clear?

Ideally there would be a LICENSE file with the full text of the MIT license and a mention of the license in the README.md.

**Comment by tsafavi** [comment]
Hello @rhofour, thank you for pointing that out! I added both a LICENSE file and a mention at the end of the README. Let me know if you have any more questions.

**Comment by rhofour** [comment]
Thanks! The license is now very clear and I no more questions.
