### ISSUE TITLE
Suggestion: Add instructions for using Explore CoDEx.ipynb with Colab

### ISSUE THREAD

**Issue by rhofour** [tsafavi/codex#4]
```
# Uncomment the lines below to install dependencies on Colab (https://colab.research.google.com).
# !git clone https://github.com/tsafavi/codex
# !pip install -r codex/requirements.txt
# !pip install -e codex/
# %cd codex

# Restart the runtime after first running this, then re-run everything.
```
Adding a comment like this at the top of Explore CoDEx.ipynb would make it easy for people to view the notebook in [colab](https://colab.research.google.com). You could even link to it directly: https://colab.research.google.com/github/tsafavi/codex/blob/master/Explore%20CoDEx.ipynb

That would make it possible for people to check this out without having to install anything on their local machine.

**Comment by tsafavi** [comment]
Hey @rhofour, thanks for the suggestion - I've added Colab installation instructions in the notebook and updated the README to link to the notebook in Colab. Let me know if you have any other questions or suggestions!
