### ISSUE TITLE
dataset extraction script

### ISSUE THREAD

**Issue by mdabedr** [tsafavi/codex#7]
Hi, is it possible to share the dataset extraction script?, i.e. given the triples.txt file, a script that extracts a dataset based on a value of k

**Comment by tsafavi** [comment]
I don't have a script that does exactly that, but to generate the CoDEx graphs I simply used [NetworkX's k-core decomposition function](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.core.k_core.html). To write such a script all you would need to do is convert the triple list to a NetworkX graph (see, e.g., the [NetworkX tutorial](https://networkx.org/documentation/stable/tutorial.html) for how to add nodes/edges to a graph), then run the k-core algorithm on the constructed graph for a given value of k.

**Comment by mdabedr** [comment]
Thanks for the quick reply. Do you have the script for the snowball sample given an initial seed set of entities and relations? In your paper you describe it as follows: "Using these seeds, we retrieved an initial set of 380,038 entities, 75 relations, and 1,156,222 triples by querying Wikidata for statements of the form (head entity of seed type, seed relation type, ?). "
